### ISSUE TITLE
Question. How I can change the language?

### ISSUE THREAD

**Issue by alfonsorios96** [t2ym/i18n-element#55]
I don't found information about methods and events for this component. I'm interesting in change language. If you can show me an example for that will be amazing ! Thanks

**Comment by t2ym** [comment]
As `i18n-element` is a wrapper class for [`i18n-behavior`](https://www.webcomponents.org/element/t2ym/i18n-behavior), you can find the documentation [here](https://www.webcomponents.org/element/t2ym/i18n-behavior) other than the syntax for [`i18n-element`](https://www.webcomponents.org/element/t2ym/i18n-element).

## Answer - How to change the language
```javascript
document.querySelector('html').lang = 'ja'; // locale for the document
```

If [`observeHtmlLang` property](https://www.webcomponents.org/element/t2ym/i18n-behavior/behaviors/BehaviorsStore.I18nBehavior#property-observeHtmlLang) is `false`, the language for a specific element can be changed via `element.lang = 'locale'`.
