### ISSUE TITLE
Desperately trying to understand

### ISSUE THREAD

**Issue by chisholmd** [t2ym/i18n-element#62]
I don't like to think of myself as a stupid person, but I am having a very hard time following your examples.
Install and then Import:
<link rel="import" href="../../bower_components/i18n-element/i18n-element.html">

Then I see an example of adding an element like this:
<localizable-element id="el1"></localizable-element>

Then I see some example contents of a localizable element like this:
<dom-module id="localizable-element">
  <template>
    <span id="label1">Localizable UI label 1</span><br>
    <span id="label2">Localizable UI label 2</span><br>
    <span id="label3">Localizable UI label 3</span>
  </template>
</dom-module>
<script>
class LocalizableElement extends Mixins.Localizable(Polymer.LegacyElementMixin(HTMLElement)) {
  static get is() { return 'localizable-element'; }
}
customElements.define(LocalizableElement.is, LocalizableElement);
</script>

So how does one relate to the other?  where does the "el1" id you set as an example when you call that element get used?   I can imagine changing those labels to en, fr, etc.  is that what I do? set the id of the element to the lang I am using?  

I am going to dig through your demo's but your demo's try to cover so much in one demo its hard to sort out what is going on.

I really appreciate you developing this component and making it available, it would be really nice to be able to understand and use it.

**Comment by t2ym** [comment]
Hi @chisholmd,

The localizable element follows the `lang` attribute of the `<html>` tag, which is set as `navigator.language` by [`i18n-preference`](https://github.com/t2ym/i18n-behavior/blob/master/i18n-preference.html) element automatically inserted by [`i18n-behavior`](https://github.com/t2ym/i18n-behavior).  `i18n-element` is a wrapper for [`i18n-behavior`](https://github.com/t2ym/i18n-behavior).

In addition to the automatic setting of the language described above, you can manually set the language of the element in DevTool console by one of these methods as well.

- `document.querySelector('html').lang = 'fr'; // set lang attribute/property of <html> element`
- `document.getElementById('el1').lang = 'fr'; // set lang attribute/property of <localizable-element>`

By default, `<localizable-element>` automatically mirrors the `lang` attribute of the `<html>` element.

Whenever the `lang` attribute is updated, `locales/localizable-element.{lang}.json` is loaded and reflected to the target element(s).

For more information, please see  [`i18n-behavior`](https://github.com/t2ym/i18n-behavior).

Are you clear on the behavior now?
